apiVersion: v1
kind: Service
metadata:
  name: refer-friends
  annotations:
    ves.io/proxy-type: HTTP_PROXY
    ves.io/app_type: arcadia-gsa
  labels:
    app: refer-friends
    service: refer-friends
spec:
  ports:
  - name: refer-friends-80
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: refer-friends-443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: refer-friends
