apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    ves.io/proxy-type: HTTP_PROXY
    ves.io/app_type: arcadia
  labels:
    app: frontend
spec:
  ports:
  - name: frontend-80
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: frontend-443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: frontend
