apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: reg.ai.local/fintech/arcadia-frontend:v5.2-rag
          imagePullPolicy: IfNotPresent
          name: frontend
          env:
            - name: service_name
              value: frontend
            - name: protocol_use
              value: "http://"
            - name: site_name
              value: "arcadia-udf"
            - name: refer_friends_fqdn
              value: "refer-friends.arcadia.svc.cluster.local"
            - name: backend_fqdn
              value: "backend.arcadia.svc.cluster.local"
            - name: "chatflowid"
              value: "6736d225-abc1-46cd-b1b5-5b4183418ca8"
            - name: "chatai_apihost"
              value: "https://llm-orch.ai.local"
            - name: "chatai_title"
              value: "Arcadia RAG on F5 UDF"
            - name: "chatai_tipmessage"
              value: "READY to help 👋!"
            - name: "chatai_agentmsg"
              value: "false"
            - name: "chatai_welcomemsg"
              value: "Welcome to F5 Protected AI Chatbot. I am here to help"
            - name: "chatai_width"
              value: "600"
            - name: "chatai_botavatar"
              value: "https://raw.githubusercontent.com/fbchan/image-public/main/bot-llm.png"
            - name: "chatai_useravatar"
              value: "https://raw.githubusercontent.com/fbchan/image-public/main/human.png"
            - name: "chatai_backgroundcolor"
              value: "#3B81F6" # default color
            - name: "chatai_customiconsrc"
              value: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/google-messages.svg"
          name: frontend
          ports:
            - containerPort: 8080
            - containerPort: 8443
              protocol: TCP
        - name: nginx-sc
          image: reg.ai.local/ngx/ngx-plus:v5.0-unpriv
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9090
          volumeMounts:
          - name: default-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: f5jsquery
            mountPath: /usr/share/nginx/html/f5jsquery.js
            subPath: f5jsquery.js
          - name: gptquery
            mountPath: /usr/share/nginx/html/gptquery.js
            subPath: gptquery.js
        - name: apigw-trading
          image: reg.ai.local/apps/arcadia-apigw:v2.3
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 4010
          volumeMounts:
          - name: api-gw
            mountPath: /usr/src/prism/api-gw.json
            subPath: api-gw.json
        - name: apigw-loadgen
          image: reg.ai.local/apps/newman:2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: fe-to-money-backend-referfriends-postman
            mountPath: /tmp/fe-to-money-backend-referfriends-postman.json
            subPath: fe-to-money-backend-referfriends-postman.json
          - name: run-apigen-fe
            mountPath: /tmp/run-apigw-loadgen.sh
            subPath: run-apigw-loadgen.sh
      volumes:
        - name: default-conf
          configMap:
             name: sc-nginx-default-conf-9090-fe-cm
        - name: api-gw
          configMap:
             name: api-gw-fe.json
        - name: fe-to-money-backend-referfriends-postman
          configMap:
             name: fe-to-money-backend-referfriends-postman.json
        - name: run-apigen-fe
          configMap:
             name: run-apigen-fe.sh
             defaultMode: 0777
        - name: f5jsquery
          configMap:
             name: f5jsquery-cm
        - name: gptquery
          configMap:
             name: gptquery-cm

