apiVersion: v1
kind: Service
metadata:
  name: money-transfer
  annotations:
    ves.io/proxy-type: HTTP_PROXY
    ves.io/app_type: arcadia-gsa
  labels:
    app: money-transfer
    service: money-transfer
spec:
  ports:
  - name: money-transfer-80
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: money-transfer-443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: money-transfer
