apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-transfer
  labels:
    app: money-transfer
    version: v1
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: money-transfer
      version: v1
  template:
    metadata:
      labels:
        app: money-transfer
        version: v1
    spec:
      containers:
        - image: reg.ai.local/fintech/arcadia-money-transfer:v5.0
          imagePullPolicy: IfNotPresent
          name: money-transfer
          env:
            - name: service_name
              value: money-transfer
            - name: site_name
              value: "arcadia-udf"
            - name: protocol_use
              value: "http://"
            - name: backend_fqdn
              value: "backend.arcadia.svc.cluster.local"
          name: money-transfer
          ports:
            - containerPort: 9080
              protocol: TCP
        - name: nginx-sc
          image: reg.ai.local/ngx/ngx-plus:v5.0-unpriv
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 8443
          volumeMounts:
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: apigw-money-transfer
          image: reg.ai.local/apps/arcadia-apigw:v2.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4010
          volumeMounts:
            - name: api-gw
              mountPath: /usr/src/prism/api-gw.json
              subPath: api-gw.json
        - name: apigw-loadgen
          image: reg.ai.local/apps/newman:2.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: east-west-mt-to-be-postman
              mountPath: /tmp/east-west-mt-to-be-postman.json
              subPath: east-west-mt-to-be-postman.json
            - name: run-apigen-mt
              mountPath: /tmp/run-apigw-loadgen.sh
              subPath: run-apigw-loadgen.sh
      volumes:
        - name: default-conf
          configMap:
            name: sc-nginx-default-conf-9090-mt-cm
        - name: api-gw
          configMap:
            name: api-gw-mt.json
        - name: east-west-mt-to-be-postman
          configMap:
            name: east-west-mt-to-be-postman.json
        - name: run-apigen-mt
          configMap:
            name: run-apigen-mt.sh
            defaultMode: 0777
